POST http://{{base_url}}/exception
Content-Type: application/json

{
  "username": "username",
  "sex": 2,
  "age": 18,
  "email": "xx@xx.com",
  "authorEmail": "xx@xx.com",
  "authorEmailI18n": "xx@xx.com",
  "testCount": 1,
  "codeCoverage": 60
}

###
GET http://{{base_url}}/programmaticValidation/noErrParam?pilotId

> {%
client.test("400", function() {
  client.assert(response.status === 400, "response status is not 200");
});
%}
###
GET http://{{base_url}}/programmaticValidation/haveErrParam?pilotId

> {%
client.test("success check", function() {
  client.assert(response.status === 200, "response status is not 200");
});
%}
